//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEUKIENSINHTHAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIEUKIENSINHTHAI()
        {
            this.VUONs = new HashSet<VUON>();
        }
    
        public int MaDKST { get; set; }
        public string Mua { get; set; }
        public string NhietDoMuaNang { get; set; }
        public string SuongMuoi { get; set; }
        public string Gio { get; set; }
        public string Lu { get; set; }
        public string TrieuCuong { get; set; }
        public Nullable<double> DoPH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VUON> VUONs { get; set; }
    }
}
