//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KIEMSOATCO
    {
        public int MaKSC { get; set; }
        public string PhuongPhap { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaKT { get; set; }
    
        public virtual KYTHUATCANHTAC KYTHUATCANHTAC { get; set; }
    }
}
