//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KS_VUNGTRONGEntities : DbContext
    {
        public KS_VUNGTRONGEntities()
            : base("name=KS_VUNGTRONGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BENHHAI> BENHHAIs { get; set; }
        public virtual DbSet<CAYTRONG> CAYTRONGs { get; set; }
        public virtual DbSet<DIAPHUONG> DIAPHUONGs { get; set; }
        public virtual DbSet<DIEUKIENSINHTHAI> DIEUKIENSINHTHAIs { get; set; }
        public virtual DbSet<DOTKHAOSAT> DOTKHAOSATs { get; set; }
        public virtual DbSet<HETHONGTUOI> HETHONGTUOIs { get; set; }
        public virtual DbSet<HIENTRANG> HIENTRANGs { get; set; }
        public virtual DbSet<KIEMSOATCO> KIEMSOATCOes { get; set; }
        public virtual DbSet<KYTHUATCANHTAC> KYTHUATCANHTACs { get; set; }
        public virtual DbSet<LOAIDAT> LOAIDATs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NONGDAN> NONGDANs { get; set; }
        public virtual DbSet<QUYENSOHUU> QUYENSOHUUs { get; set; }
        public virtual DbSet<SAUHAI> SAUHAIs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VUON> VUONs { get; set; }
    }
}
