//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYENSOHUU
    {
        public int MaSoHuu { get; set; }
        public Nullable<int> MaVuon { get; set; }
        public Nullable<int> MaND { get; set; }
        public Nullable<int> MaDot { get; set; }
    
        public virtual DOTKHAOSAT DOTKHAOSAT { get; set; }
        public virtual NONGDAN NONGDAN { get; set; }
        public virtual VUON VUON { get; set; }
    }
}
